[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
jclass = {path = "../jclass"}
jdescriptor = {path = "../jdescriptor"}
indexmap = { version = "2.5.0" , features = ["serde"]}
once_cell = "1.20.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.132"
