[package]
name = "jimage-rs"
version = "0.0.1"
edition = "2021"

workspace = ".."

[dependencies]
memmap2 = "0.9.5"
memchr = "2.7.5"
flate2 = "1.1.2"
thiserror = "2.0.12"
clap = { version = "4.5.40", features = ["derive"] }
