name: Big-Endian Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  big-endian-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust (Nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: powerpc-unknown-linux-gnu

      - name: Install QEMU
        run: sudo apt-get install -y qemu-user

      - name: Build for Big-Endian
        run: cargo build --target=powerpc-unknown-linux-gnu

      - name: Run Tests with QEMU
        run: qemu-ppc target/powerpc-unknown-linux-gnu/debug/your_binary
