name: Big Endian Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-on-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Run tests in s390x container
        run: |
          docker run --rm --platform linux/s390x -v "$(pwd)":/app s390x/ubuntu bash -c "
            set -e
            apt-get update &&
            apt-get install -y build-essential curl &&
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
            export PATH=\$HOME/.cargo/bin:\$PATH &&  # Fix: Explicitly add Cargo bin to PATH
            cd /app &&
            cargo test
          "
