name: Big-Endian Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build the custom Docker image for PowerPC64
      - name: Build Docker Image
        run: |
          cat <<EOF > Dockerfile
          FROM debian:bullseye

          # Install required tools
          RUN apt-get update && apt-get install -y \
              build-essential \
              gcc-powerpc64-linux-gnu \
              curl \
              qemu-user \
              && rm -rf /var/lib/apt/lists/*

          # Install Rust, set PATH, and install Zig in a single RUN command to ensure cargo is available
          RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
          && export PATH="/root/.cargo/bin:${PATH}" \
          && curl -LO https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz \
          && tar -xvf zig-linux-x86_64-0.13.0.tar.xz \
          && mv zig-linux-x86_64-0.13.0 /usr/local/zig \
          && export PATH="/usr/local/zig/zig-linux-x86_64-0.13.0:${PATH}" \
          && cargo install cargo-zigbuild \
          && rustup target add powerpc64-unknown-linux-gnu
          EOF

          # Build the Docker image
          docker build -t custom-rust-powerpc64 .

      # Step 3: Run the build using the Docker image
      - name: Build for PowerPC64
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project custom-rust-powerpc64 \
          cargo zigbuild --target=powerpc64-unknown-linux-gnu

      # Step 4: Run tests (optional)
      - name: Run Tests (Optional)
        run: |
          docker run --rm -v ${{ github.workspace }}:/project -w /project custom-rust-powerpc64 \
          cargo test --target=powerpc64-unknown-linux-gnu
