name: Zip Standard Library Classes and Upload on Release
on:
  release:
    types: [published]
jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate zip file name
        run: |
          echo "ZIP_NAME=std-lib-${{ github.event.release.tag_name }}.zip" >> "$GITHUB_ENV"

      - name: Zipping folder
        run: |
          find lib -name "*.class" | zip "$ZIP_NAME" -@

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
