name: Zip Standard Library Classes and Upload on Release
on:
  release:
    types: [published]
jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zipping folder
        run: |
          zip -r ${{ github.event.release.tag_name }}-lib.zip lib -i '*.class'

      - name: Upload release asset
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: ${{ github.event.release.tag_name }}-lib.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_CLASSIC }}
